### PR TITLE
Support Crystal v0.31

### PR DESCRIPTION
**Pull request by da1nerd**
* removed deprecated asking syntax from variables

### CODE REVIEW

**Comment by Qard** [comment]
I ran into the same issue. Here's where they removed support for `?` in variable names--it was a bug that it ever worked, apparently. https://github.com/crystal-lang/crystal/pull/7582

**Comment by nhh** [comment]
I ran into the same issue and fixed it. Thought it would be something introduced with crystal 1.0.0

I also fixed the tests. It seems that this library is abandoned?

**Comment by da1nerd** [comment]
@nulldotpro are you maintaining this shard anymore?

**Comment by da1nerd** [comment]
I'd be interested in helping to maintain this and also https://github.com/nulldotpro/LibGLFW.
@nhh it looks like you've already made a lot of improvements.

**Comment by nhh** [comment]
Thank you! I only did small changes. :) Its a impressive code base and very nice topic to wrap your head around. I would also participate in maintenance if needed.

**Comment by calebuharrison** [comment]
@da1nerd @nhh Thank you both for reaching out - apologies for being so late to respond!

I don't use this library currently, but I put a lot of love into it when I put it together. I would welcome any help getting it back into shape. It seems like #10 has identical fixes to this PR, but with an additional tweak. I'll close this PR and merge the other one.

**Comment by da1nerd** [comment]
Thanks @nulldotpro! if you don't have the time maintain this shard, you could add a couple of people from the community as contributors so they can manage pull requests and make updates.

**Pull request merged**
